export const chainPassAbi = [
  {
    type: 'function',
    name: 'createEvent',
    stateMutability: 'payable',
    inputs: [
      {
        name: 'p',
        type: 'tuple',
        components: [
          { name: 'name', type: 'string' },
          { name: 'venue', type: 'string' },
          { name: 'ticketPrice', type: 'uint256' },
          { name: 'maxSupply', type: 'uint256' },
          { name: 'saleStartTime', type: 'uint256' },
          { name: 'saleEndTime', type: 'uint256' },
          { name: 'eventStartTime', type: 'uint256' },
          { name: 'eventEndTime', type: 'uint256' },
        ],
      },
    ],
    outputs: [{ name: 'eventId', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'buyTicket',
    stateMutability: 'payable',
    inputs: [{ name: 'eventId', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'listForResale',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'tokenId', type: 'uint256' },
      { name: 'resalePrice', type: 'uint256' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'buyResaleTicket',
    stateMutability: 'payable',
    inputs: [{ name: 'tokenId', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'cancelResaleListing',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'tokenId', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'submitReview',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'eventId', type: 'uint256' },
      { name: 'contentHash', type: 'string' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'requestReviewDropWinner',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'eventId', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'getEvent',
    stateMutability: 'view',
    inputs: [{ name: 'eventId', type: 'uint256' }],
    outputs: [
      {
        name: '',
        type: 'tuple',
        components: [
          { name: 'eventId', type: 'uint256' },
          { name: 'organiser', type: 'address' },
          { name: 'ticketPrice', type: 'uint256' },
          { name: 'maxSupply', type: 'uint256' },
          { name: 'totalMinted', type: 'uint256' },
          { name: 'saleStartTime', type: 'uint256' },
          { name: 'saleEndTime', type: 'uint256' },
          { name: 'eventStartTime', type: 'uint256' },
          { name: 'eventEndTime', type: 'uint256' },
          { name: 'organiserStake', type: 'uint256' },
          { name: 'stakeReturned', type: 'bool' },
          { name: 'exists', type: 'bool' },
        ],
      },
    ],
  },
  {
    type: 'function',
    name: 'getTotalEvents',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'getTotalTicketsMinted',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'getWalletTickets',
    stateMutability: 'view',
    inputs: [{ name: 'wallet', type: 'address' }],
    outputs: [{ name: '', type: 'uint256[]' }],
  },
  {
    type: 'function',
    name: 'ticketsBought',
    stateMutability: 'view',
    inputs: [
      { name: '', type: 'uint256' },
      { name: '', type: 'address' },
    ],
    outputs: [{ name: '', type: 'uint256' }],
  },
] as const
